name: Scrape Melody Playlist

on:
  schedule:
    - cron: "*/5 * * * *"   # každých ~5 min (best-effort)
  workflow_dispatch:        # manuálne spustenie

permissions:
  contents: write           # povolenie na commit/push

# zabráni súbežným behom na rovnakej vetve
concurrency:
  group: playlist-main
  cancel-in-progress: true

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo (full history)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0      # dôležité pre rebase

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run scraper
        run: python scraper.py

      # Commitujeme len pri úspechu scraperu
      - name: Commit & push (commit → rebase → push)
        if: success()
        env:
          TZ: Europe/Bratislava   # lokálny čas v commit message
        run: |
          set -e
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          # 1) Najprv commitni lokálne zmeny (ak nejaké sú)
          git add -A
          if git diff --cached --quiet; then
            echo "No changes."
            exit 0
          fi

          ts=$(date +'%Y-%m-%dT%H:%M:%S%z')   # napr. 2025-10-02T08:54:43+0200
          git commit -m "update playlist $ts"

          # 2) Potom zarovnaj históriu na remote (rebase + autostash)
          git pull --rebase --autostash origin main

          # 3) Nakoniec push (s krátkym retry v prípade pretekov)
          for i in 1 2 3; do
            if git push; then
              echo "Push OK"
              break
            fi
            echo "Push failed, retrying ($i)..."
            git pull --rebase --autostash origin main
          done
