name: Scrape Melody Playlist

on:
  schedule:
    - cron: "*/5 * * * *"   # aspoň každých 5 minút
  workflow_dispatch:        # možnosť spustiť ručne

permissions:
  contents: write           # povolenie na commit/push

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run scraper
        run: |
          python scraper.py

      - name: Commit & push if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          if [[ -n "$(git status --porcelain)" ]]; then
            git add -A
            git commit -m "update playlist $(date -u +'%Y-%m-%dT%H:%M:%SZ')"
            git push
          else
            echo "No changes."
          fi
